### PR TITLE
Added to_snake_case helper method

### LINKED ISSUE #1: Convert CamelCase enum variants to snake_case
For example,

```rust
enum MyEnum {
    SomeVariant(i32),
}
```

will have a member generated as `fn somevariant(&self) -> ...`. Although it is a breaking change, I want it to automatically convert to its snake_case name, i.e. `some_variant`.

### PR DESCRIPTION
**Pull request by TheDan64**
Hi! You've got a neat crate going on here. Hope you continue to improve it!

1) Sorry my editor stripped a bunch of whitespace. If this bothers you I can add it back in
2) test_getter_structs L61 is still `third.somestruct()` Maybe you could point me in the right direction for fixing that one?
3) Note my hilariously ugly (but working) first attempt at being clever with iterators:
```rust
fn to_snake_case(ident: &Ident) -> String {
    fn add_underscore(size_char: (usize, char)) -> String {
        let (i, c) = size_char;

        if i > 0 && c.is_uppercase() {
            "_".chars()
               .zip(c.to_lowercase())
               .map(|(c1, c2)| format!("{}{}", c1, c2))
               .next()
               .unwrap()
        } else {
            c.to_lowercase()
             .next()
             .unwrap()
             .to_string()
        }
    };

    ident.as_ref()
         .chars()
         .enumerate()
         .map(add_underscore)
         .collect::<String>()
         .into()
}
```

Fixed #1

### CODE REVIEW

**Comment by alekratz** [comment]
Hey, thanks for the PR! I'll take a look at it soon (hopefully within the weekend).

**Comment by alekratz** [comment]
> Sorry my editor stripped a bunch of whitespace. If this bothers you I can add it back in

No worries :) I'm not super strict about that stuff.

> test_getter_structs L61 is still third.somestruct() Maybe you could point me in the right direction for fixing that one?

That one is actually defined just above at [L46](https://github.com/alekratz/enum-methods/blob/04ad7fe6e70b9a2bd84a721a78f4e9e282dc072c/tests/test_getters.rs#L46). This is because getters for structs are not currently implemented, because I hadn't thought of a good naming scheme for that yet (I just added #3 while typing this now), so I'm using it as a way to confirm that it's *not* being added, because that's expected behavior (if that makes sense).

> Note my hilariously ugly (but working) first attempt at being clever with iterators:

I may get excommunicated for this, but all of this happens during compile time, so speed and memory usage *probably* doesn't make much of a difference. I laud your cleverness with iterators and honestly it's what I would have done myself.

**Comment by TheDan64** [comment]
Haha, thanks. Makes sense! I ended up just choosing the solution that was easier to read.

**Comment by alekratz** [comment]
I've reviewed your changes, and they look good. I'll be updating the documentation to reflect what has been changed. Thanks a lot.

**Comment by alekratz** [comment]
Oh, sorry, I forgot to mention, I can add you to an AUTHORS.md file (or something similar) if you want. :)

**Comment by TheDan64** [comment]
Sure, whatever format you prefer would be fine

**Pull request merged**
